# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Analysis for Sale
# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  The portfolio site for software developer Gregory J Crowder.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gcrowder.github.io" # the base hostname & protocol for your site
twitter_username: tievape
github_username:  gcrowder
linkedin_username: gregory-crowder-96b72612

# Build settings
markdown: kramdown
